FROM ubuntu:20.04
COPY iptables /etc/network/if-up.d/iptables
WORKDIR /opt/Dockovpn
COPY scripts .
COPY config ./config
COPY VERSION ./config
RUN apt update &&\
    apt install -y\
    tzdata \
    iptables \
    ipset \
    openvpn easy-rsa bash netcat-openbsd zip dumb-init && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime &&\
    dpkg-reconfigure -f noninteractive tzdata &&\
    chmod +x /etc/network/if-up.d/iptables
RUN apt install -y \
    # curl \
    # net-tools mc telnet vim iputils-ping \
    tor \
    tor-geoipdb \
 #   privoxy \
 #   squid3 \
     \
    supervisor \
    obfs4proxy &&\
    rm -rf /var/lib/apt/lists/*
COPY torrc /etc/tor/torrc
COPY blocektip.txt ./blocektip.txt
#COPY privoxy.conf /etc/privoxy/config
#COPY squid.conf /etc/squid/squid.conf
#COPY redirect-to-tor.txt /etc/squid/redirect-to-tor.dat
# supervisor config
COPY supervisor.conf /etc/supervisor/conf.d/tor_proxy.conf
##Конфижим openvpn
EXPOSE 1194/udp
EXPOSE 8080/tcp
RUN mkdir -p /opt/Dockovpn_data && \
    cd /opt/Dockovpn_data && \
    /usr/share/easy-rsa/easyrsa init-pki && \
    /usr/share/easy-rsa/easyrsa gen-dh && \
    # DH parameters of size 2048 created at /usr/share/easy-rsa/pki/dh.pem
    # Copy DH file
    cp pki/dh.pem /etc/openvpn && \
    # Copy FROM ./scripts/server/conf TO /etc/openvpn/server.conf in DockerFile
    cd /opt/Dockovpn && \
    cp config/server.conf /etc/openvpn/server.conf &&\
    groupadd nobody
RUN ./genclient.sh
VOLUME [ "/opt/Dockovpn_data" ]
CMD ["/usr/bin/supervisord"]